### PR TITLE
improvements

### PR DESCRIPTION
**Pull request by Flucadetena**
Trying to enhance user experience, I updated the way dates are selected.

Currently a user must select the day last for the "selectedDate" to change. But I've seen that a lot of the times, the user selects the day first and then the month or year, and changes multiple times. And until he selects the day, the new date is not selected.
I believe that it is more intuitive that the state of the day or month stays the same, if posible, through the changes. So now:

-If a user selects a day, and then the month. In the new month the preselected day will be chosen.

EXAMPLE: User selects the 29th of jan. Then changes to March, the 29th of March is selected. In the case that the selected month doesn't have that date available(Feb, for example), it will select the first available date of the month. If no day is available, It will keep the previously selected date and fire the function "OnNoAvailableDate", so the developer can choose how to let the user Know that there are no available dates on that month and the last selected date is the current one.

I also added lints to encourage good coding practices and easier development.

Hope It helps as always!, Love this Package ;)

### CODE REVIEW

**Comment by ikicodedev** [comment]
Hi @Flucadetena, 

Thanks for the improvement. I am doing tests before integrating the PR and I have found this issue: When I change from January to February the list of days does not scroll correctly.

https://user-images.githubusercontent.com/5318708/149906257-205589a7-80e0-435e-a018-5bbd17be3c45.mov

.

**Comment by Flucadetena** [comment]
Hi @ikicodedev I'm very sorry for delaying so much to answer, but I wanted to test back everything and couldn't find the time. 

It is working as expected. At least how I programed it.
When you change to a knew month it tries to change to the same date. If the date is not available or doesn't exist, like in the case shown in the video (29 of Feb), it will select the first available date on that month.
If there are no months available in that month it will prompt a toast saying there are no available dates on that month.

If you have any further questions or suggestions let me know and I'll adapt ;)

**Comment by ikicodedev** [comment]
Hi @Flucadetena, I have been talking with my UX teammate and the behavior you have added is not a valid pattern in the use case of this widget. Therefore, I cannot accept this PR. Sorry.

**Comment by Flucadetena** [comment]
No problem @ikicodedev ;)

**Pull request closed without merging**
